# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='validate',
        ),
    ]
