# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
    ]
